import '@servicenow/sdk/global'
import { BusinessRule, ClientScript } from '@servicenow/sdk/core'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded successfully!!' message everytime todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!!")
    }`,
})

ClientScript({
    $id: Now.ID['cs1'],
    name: 'my_client_script1',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 1")
    }`,
})

ClientScript({
    $id: Now.ID['cs2'],
    name: 'my_client_script2',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 2")
    }`,
})

ClientScript({
    $id: Now.ID['cs3'],
    name: 'my_client_script3',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 3")
    }`,
})

// Repeat for cs4 to cs100

ClientScript({
    $id: Now.ID['cs4'],
    name: 'my_client_script4',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 4")
    }`,
})

ClientScript({
    $id: Now.ID['cs5'],
    name: 'my_client_script5',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 5")
    }`,
})

ClientScript({
    $id: Now.ID['cs6'],
    name: 'my_client_script6',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 6")
    }`,
})

ClientScript({
    $id: Now.ID['cs7'],
    name: 'my_client_script7',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 7")
    }`,
})

ClientScript({
    $id: Now.ID['cs8'],
    name: 'my_client_script8',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 8")
    }`,
})

ClientScript({
    $id: Now.ID['cs9'],
    name: 'my_client_script9',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 9")
    }`,
})

ClientScript({
    $id: Now.ID['cs10'],
    name: 'my_client_script10',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 10")
    }`,
})

ClientScript({
    $id: Now.ID['cs11'],
    name: 'my_client_script11',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 11")
    }`,
})

ClientScript({
    $id: Now.ID['cs12'],
    name: 'my_client_script12',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 12")
    }`,
})

ClientScript({
    $id: Now.ID['cs13'],
    name: 'my_client_script13',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 13")
    }`,
})

ClientScript({
    $id: Now.ID['cs14'],
    name: 'my_client_script14',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 14")
    }`,
})

ClientScript({
    $id: Now.ID['cs15'],
    name: 'my_client_script15',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 15")
    }`,
})


ClientScript({
    $id: Now.ID['cs16'],
    name: 'my_client_script16',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 16")
    }`,
})

ClientScript({
    $id: Now.ID['cs17'],
    name: 'my_client_script17',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 17")
    }`,
})

ClientScript({
    $id: Now.ID['cs18'],
    name: 'my_client_script18',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 18")
    }`,
})

ClientScript({
    $id: Now.ID['cs19'],
    name: 'my_client_script19',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 19")
    }`,
})

ClientScript({
    $id: Now.ID['cs20'],
    name: 'my_client_script20',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 20")
    }`,
})

ClientScript({
    $id: Now.ID['cs21'],
    name: 'my_client_script21',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 21")
    }`,
})

ClientScript({
    $id: Now.ID['cs22'],
    name: 'my_client_script22',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 22")
    }`,
})

ClientScript({
    $id: Now.ID['cs23'],
    name: 'my_client_script23',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 23")
    }`,
})

ClientScript({
    $id: Now.ID['cs24'],
    name: 'my_client_script24',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 24")
    }`,
})

ClientScript({
    $id: Now.ID['cs25'],
    name: 'my_client_script25',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 25")
    }`,
})

ClientScript({
    $id: Now.ID['cs26'],
    name: 'my_client_script26',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 26")
    }`,
})

ClientScript({
    $id: Now.ID['cs27'],
    name: 'my_client_script27',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 27")
    }`,
})

ClientScript({
    $id: Now.ID['cs28'],
    name: 'my_client_script28',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 28")
    }`,
})

ClientScript({
    $id: Now.ID['cs29'],
    name: 'my_client_script29',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 29")
    }`,
})

ClientScript({
    $id: Now.ID['cs30'],
    name: 'my_client_script30',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 30")
    }`,
})


ClientScript({
    $id: Now.ID['cs31'],
    name: 'my_client_script31',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 31")
    }`,
})

ClientScript({
    $id: Now.ID['cs32'],
    name: 'my_client_script32',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 32")
    }`,
})

ClientScript({
    $id: Now.ID['cs33'],
    name: 'my_client_script33',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 33")
    }`,
})

ClientScript({
    $id: Now.ID['cs34'],
    name: 'my_client_script34',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 34")
    }`,
})

ClientScript({
    $id: Now.ID['cs35'],
    name: 'my_client_script35',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 35")
    }`,
})

ClientScript({
    $id: Now.ID['cs36'],
    name: 'my_client_script36',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 36")
    }`,
})

ClientScript({
    $id: Now.ID['cs37'],
    name: 'my_client_script37',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 37")
    }`,
})

ClientScript({
    $id: Now.ID['cs38'],
    name: 'my_client_script38',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 38")
    }`,
})

ClientScript({
    $id: Now.ID['cs39'],
    name: 'my_client_script39',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 39")
    }`,
})

ClientScript({
    $id: Now.ID['cs40'],
    name: 'my_client_script40',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 40")
    }`,
})

ClientScript({
    $id: Now.ID['cs41'],
    name: 'my_client_script41',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 41")
    }`,
})

ClientScript({
    $id: Now.ID['cs42'],
    name: 'my_client_script42',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 42")
    }`,
})

ClientScript({
    $id: Now.ID['cs43'],
    name: 'my_client_script43',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 43")
    }`,
})

ClientScript({
    $id: Now.ID['cs44'],
    name: 'my_client_script44',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 44")
    }`,
})

ClientScript({
    $id: Now.ID['cs45'],
    name: 'my_client_script45',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 45")
    }`,
})

ClientScript({
    $id: Now.ID['cs46'],
    name: 'my_client_script46',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 46")
    }`,
})

ClientScript({
    $id: Now.ID['cs47'],
    name: 'my_client_script47',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 47")
    }`,
})

ClientScript({
    $id: Now.ID['cs48'],
    name: 'my_client_script48',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 48")
    }`,
})


ClientScript({
    $id: Now.ID['cs49'],
    name: 'my_client_script49',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 49")
    }`,
})

ClientScript({
    $id: Now.ID['cs50'],
    name: 'my_client_script50',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 50")
    }`,
})

ClientScript({
    $id: Now.ID['cs51'],
    name: 'my_client_script51',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 51")
    }`,
})

ClientScript({
    $id: Now.ID['cs52'],
    name: 'my_client_script52',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 52")
    }`,
})

ClientScript({
    $id: Now.ID['cs53'],
    name: 'my_client_script53',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 53")
    }`,
})

ClientScript({
    $id: Now.ID['cs54'],
    name: 'my_client_script54',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 54")
    }`,
})

ClientScript({
    $id: Now.ID['cs55'],
    name: 'my_client_script55',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 55")
    }`,
})

ClientScript({
    $id: Now.ID['cs56'],
    name: 'my_client_script56',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 56")
    }`,
})

ClientScript({
    $id: Now.ID['cs57'],
    name: 'my_client_script57',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 57")
    }`,
})

ClientScript({
    $id: Now.ID['cs58'],
    name: 'my_client_script58',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 58")
    }`,
})

ClientScript({
    $id: Now.ID['cs59'],
    name: 'my_client_script59',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 59")
    }`,
})

ClientScript({
    $id: Now.ID['cs60'],
    name: 'my_client_script60',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 60")
    }`,
})

ClientScript({
    $id: Now.ID['cs61'],
    name: 'my_client_script61',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 61")
    }`,
})

ClientScript({
    $id: Now.ID['cs62'],
    name: 'my_client_script62',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 62")
    }`,
})

ClientScript({
    $id: Now.ID['cs63'],
    name: 'my_client_script63',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 63")
    }`,
})

ClientScript({
    $id: Now.ID['cs64'],
    name: 'my_client_script64',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 64")
    }`,
})

ClientScript({
    $id: Now.ID['cs65'],
    name: 'my_client_script65',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 65")
    }`,
})

ClientScript({
    $id: Now.ID['cs66'],
    name: 'my_client_script66',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 66")
    }`,
})


ClientScript({
    $id: Now.ID['cs67'],
    name: 'my_client_script67',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 67")
    }`,
})

ClientScript({
    $id: Now.ID['cs68'],
    name: 'my_client_script68',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 68")
    }`,
})

ClientScript({
    $id: Now.ID['cs69'],
    name: 'my_client_script69',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 69")
    }`,
})

ClientScript({
    $id: Now.ID['cs70'],
    name: 'my_client_script70',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 70")
    }`,
})

ClientScript({
    $id: Now.ID['cs71'],
    name: 'my_client_script71',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 71")
    }`,
})

ClientScript({
    $id: Now.ID['cs72'],
    name: 'my_client_script72',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 72")
    }`,
})

ClientScript({
    $id: Now.ID['cs73'],
    name: 'my_client_script73',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 73")
    }`,
})

ClientScript({
    $id: Now.ID['cs74'],
    name: 'my_client_script74',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 74")
    }`,
})

ClientScript({
    $id: Now.ID['cs75'],
    name: 'my_client_script75',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 75")
    }`,
})

ClientScript({
    $id: Now.ID['cs76'],
    name: 'my_client_script76',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 76")
    }`,
})

ClientScript({
    $id: Now.ID['cs77'],
    name: 'my_client_script77',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 77")
    }`,
})

ClientScript({
    $id: Now.ID['cs78'],
    name: 'my_client_script78',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 78")
    }`,
})

ClientScript({
    $id: Now.ID['cs79'],
    name: 'my_client_script79',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 79")
    }`,
})

ClientScript({
    $id: Now.ID['cs80'],
    name: 'my_client_script80',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 80")
    }`,
})

ClientScript({
    $id: Now.ID['cs81'],
    name: 'my_client_script81',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 81")
    }`,
})

ClientScript({
    $id: Now.ID['cs82'],
    name: 'my_client_script82',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 82")
    }`,
})

ClientScript({
    $id: Now.ID['cs83'],
    name: 'my_client_script83',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 83")
    }`,
})

ClientScript({
    $id: Now.ID['cs84'],
    name: 'my_client_script84',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 84")
    }`,
})



ClientScript({
    $id: Now.ID['cs85'],
    name: 'my_client_script85',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 85")
    }`,
})

ClientScript({
    $id: Now.ID['cs86'],
    name: 'my_client_script86',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 86")
    }`,
})

ClientScript({
    $id: Now.ID['cs87'],
    name: 'my_client_script87',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 87")
    }`,
})

ClientScript({
    $id: Now.ID['cs88'],
    name: 'my_client_script88',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 88")
    }`,
})

ClientScript({
    $id: Now.ID['cs89'],
    name: 'my_client_script89',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 89")
    }`,
})

ClientScript({
    $id: Now.ID['cs90'],
    name: 'my_client_script90',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 90")
    }`,
})

ClientScript({
    $id: Now.ID['cs91'],
    name: 'my_client_script91',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 91")
    }`,
})

ClientScript({
    $id: Now.ID['cs92'],
    name: 'my_client_script92',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 92")
    }`,
})

ClientScript({
    $id: Now.ID['cs93'],
    name: 'my_client_script93',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 93")
    }`,
})

ClientScript({
    $id: Now.ID['cs94'],
    name: 'my_client_script94',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 94")
    }`,
})

ClientScript({
    $id: Now.ID['cs95'],
    name: 'my_client_script95',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 95")
    }`,
})

ClientScript({
    $id: Now.ID['cs96'],
    name: 'my_client_script96',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 96")
    }`,
})

ClientScript({
    $id: Now.ID['cs97'],
    name: 'my_client_script97',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 97")
    }`,
})

ClientScript({
    $id: Now.ID['cs98'],
    name: 'my_client_script98',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 98")
    }`,
})

ClientScript({
    $id: Now.ID['cs99'],
    name: 'my_client_script99',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 99")
    }`,
})

ClientScript({
    $id: Now.ID['cs100'],
    name: 'my_client_script100',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!! Script 100")
    }`,
})


// additional business rules with unique ids and names
BusinessRule({
    $id: Now.ID['br1'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange1',
    order: 101,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br2'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange2',
    order: 102,
    when: 'before',
    active: true,
    abort_action: false,
})

// repeat the same pattern for the remaining 18 business rules
BusinessRule({
    $id: Now.ID['br3'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange3',
    order: 103,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br4'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange4',
    order: 104,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br5'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange5',
    order: 105,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br6'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange6',
    order: 106,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br7'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange7',
    order: 107,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br8'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange8',
    order: 108,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br9'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange9',
    order: 109,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br10'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange10',
    order: 110,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br11'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange11',
    order: 111,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br12'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange12',
    order: 112,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br13'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange13',
    order: 113,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br14'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange14',
    order: 114,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br15'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange15',
    order: 115,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br16'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange16',
    order: 116,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br17'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange17',
    order: 117,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br18'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange18',
    order: 118,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br19'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange19',
    order: 119,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br20'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange20',
    order: 120,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br21'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange21',
    order: 121,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br22'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange22',
    order: 122,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br23'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange23',
    order: 123,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br24'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange24',
    order: 124,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br25'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange25',
    order: 125,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br26'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange26',
    order: 126,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br27'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange27',
    order: 127,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br28'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange28',
    order: 128,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br29'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange29',
    order: 129,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br30'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange30',
    order: 130,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br31'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange31',
    order: 131,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br32'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange32',
    order: 132,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br33'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange33',
    order: 133,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br34'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange34',
    order: 134,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br35'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange35',
    order: 135,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br36'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange36',
    order: 136,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br37'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange37',
    order: 137,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br38'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange38',
    order: 138,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br39'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange39',
    order: 139,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br40'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange40',
    order: 140,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br41'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange41',
    order: 141,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br42'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange42',
    order: 142,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br43'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange43',
    order: 143,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br44'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange44',
    order: 144,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br45'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange45',
    order: 145,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br46'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange46',
    order: 146,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br47'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange47',
    order: 147,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br48'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange48',
    order: 148,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br49'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange49',
    order: 149,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br50'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange50',
    order: 150,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br51'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange51',
    order: 151,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br52'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange52',
    order: 152,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br53'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange53',
    order: 153,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br54'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange54',
    order: 154,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br55'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange55',
    order: 155,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br56'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange56',
    order: 156,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br57'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange57',
    order: 157,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br58'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange58',
    order: 158,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br59'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange59',
    order: 159,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br60'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange60',
    order: 160,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br61'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange61',
    order: 161,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br62'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange62',
    order: 162,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br63'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange63',
    order: 163,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br64'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange64',
    order: 164,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br65'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange65',
    order: 165,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br66'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange66',
    order: 166,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br67'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange67',
    order: 167,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br68'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange68',
    order: 168,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br69'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange69',
    order: 169,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br70'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange70',
    order: 170,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br71'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange71',
    order: 171,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br72'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange72',
    order: 172,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br73'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange73',
    order: 173,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br74'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange74',
    order: 174,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br75'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange75',
    order: 175,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br76'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange76',
    order: 176,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br77'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange77',
    order: 177,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br78'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange78',
    order: 178,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br79'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange79',
    order: 179,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br80'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange80',
    order: 180,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br81'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange81',
    order: 181,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br82'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange82',
    order: 182,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br83'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange83',
    order: 183,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br84'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange84',
    order: 184,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br85'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange85',
    order: 185,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br86'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange86',
    order: 186,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br87'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange87',
    order: 187,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br88'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange88',
    order: 188,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br89'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange89',
    order: 189,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br90'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange90',
    order: 190,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br91'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange91',
    order: 191,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br92'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange92',
    order: 192,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br93'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange93',
    order: 193,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br94'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange94',
    order: 194,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br95'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange95',
    order: 195,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br96'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange96',
    order: 196,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br97'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange97',
    order: 197,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br98'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange98',
    order: 198,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br99'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange99',
    order: 199,
    when: 'before',
    active: true,
    abort_action: false,
})

BusinessRule({
    $id: Now.ID['br100'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange100',
    order: 200,
    when: 'before',
    active: true,
    abort_action: false,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})
